name: Linux-AArch64-RPi4B-bcm2711

on: [push, pull_request]

jobs:  
  build:
    name: build-linux-aarch64-rpi4b-bcm2711
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Config & Build
        with:
          arch: aarch64
          distro: archarm_latest
          run:
            make -j4 ARCH=arm64 bcm2711_defconfig
            make -j4 ARCH=arm64
